#https://hub.docker.com/_/mongo
networks:
  network: {}
services:
  frontend:
    build: .
    image: "dvnosqli:0.0"
    volumes:
      - "./src/php:/var/www/html"
    ports: 
      - "8084:8080"
    networks:
      - network
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  neo4j:
    image: "neo4j:community"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes: 
      - "./.data:/data:rw"
    networks:
      - network
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - network
  mongo-frontend:
    image: mongo-express
    depends_on:
      - "mongo"
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    ports: 
      - "8081:8081"
    networks:
      - network
    restart: unless-stopped

